# -*- coding: utf-8 -*-
"""labcycleq1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4nZRip9lm61THzf6DNxHNLpBH0oP2af

Develop a program to read a four-digit number and find its

  a. Sum of digits

  b. Reverse
  
  c. Difference between the product of digits at the odd position
and the product of digits at the even position.
"""

def digits_number(n):
  d1=(n//1000)%10 #finding digit1
  d2=(n//100)%10  #finding digit2
  d3=(n//10)%10   #finding digit3
  d4=n%10         #finding digit4
  return d1,d2,d3,d4

#function to find sum
def find_sum(d1,d2,d3,d4):
  sum=d1+d2+d3+d4
  print("Sum: ",sum)
  
#function to find reverse
def reverse_of_number(d1,d2,d3,d4):
  reverse = (d4*1000) + (d3*100) + (d2*10) + d1
  print("Reverse: ",reverse)

#function to find reverse
def find_difference(d1,d2,d3,d4):
  difference=(d1*d3)-(d2*d4) #finding difference of products
  print("Difference: ",difference)

num=int(input("Enter a number: "))
print("Number: ",num)
#calling functions
digit1,digit2,digit3,digit4 = digits_number(num)
find_sum(digit1,digit2,digit3,digit4)
reverse_of_number(digit1,digit2,digit3,digit4)
find_difference(digit1,digit2,digit3,digit4)