# -*- coding: utf-8 -*-
"""labcycleq4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1duyYAMSitPyhdO4HktJ1psYi2GfUCFkE

Develop a program to perform the following task:

a. Define a function to check whether a number is happy or not.

b. Define a function to print all happy numbers within a range.

c. Define a function to print first N happy numbers
"""

def check_happy(n): #fuction to check whether a number is happy or sad
  

  for i in range(0,101):
    sum = 0
    while(n>0):
      digit=n%10
      n=n//10
      sum=sum+digit**2
    n=sum
    if(sum==1):
      return True
      
  else:
       return False

    
def range_happy(l,u): #function to print happy numbers within a range
  for i in range(l,u+1):
      if check_happy(i):
        print(i,end=" ")


def print_firstN(N): #function to print first n happy numbers
  count=0
  i=0
  while count<N:
      i=i+1
      if check_happy(i):
        print(i,end=" ")
        count=count+1
      else:
        continue 

num=int(input("Enter a number to check whether happy or sad: "))
ans = check_happy(num)
if ans:
  print(num," is a happy number")
else:
  print(num," is a sad number")
print("\n")
print("Happy numbers within a range")
lower_limit=int(input("Enter the lower limit: "))
upper_limit=int(input("Enter the upper limit: "))
range_happy(lower_limit,upper_limit) #calling function
print("\n")
print("First N happy numbers")
no_of_terms=int(input("Enter the number of happy numbers: ")) 
print_firstN(no_of_terms)  #calling function
