# -*- coding: utf-8 -*-
"""labcycle2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EVqsWZRSoaYbe6sWUgXmwqM8tCm0zgAB

Develop a program to read the three sides of two triangles and calculate the area of both. Define a function to read the three sides and call it. Also, define a function to calculate the area. Print the total area enclosed by both triangles and each triangle's contribution (%) towards it.
"""

def read_sides(): #fuction to read the sides of triangle
  a = int(input("Enter length of side1: "))
  b = int(input("Enter length of side2: "))
  c = int(input("Enter length of side3: "))
  return(a,b,c)

def area_triangle(a,b,c): #function to find area of the two triangles
  s=(a+b+c)/2
  area= (s*(s-a)*(s-b)*(s-c))** 0.5
  return(area)

print("Triangle 1 : ")  #printing area of both the triangles
A,B,C=read_sides()  #calling function
print("Area of triangle 1 is ",area_triangle(A,B,C))
print("\n")
print("Triangle 2: ")
X,Y,Z=read_sides()  #calling function
print("Area of triangle 2 is ",area_triangle(X,Y,Z))
print("\n")
totalarea= area_triangle(A,B,C)+area_triangle(X,Y,Z)
print("Total area= ",totalarea)
print("Contribution of triangle1 = ",(area_triangle(A,B,C)/totalarea)*100,"%")
print("Contribution of triangle2  = ",(area_triangle(X,Y,Z)/totalarea)*100,"%")
