# -*- coding: utf-8 -*-
"""lab3q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11eNAleYdx9du9_XgefiCemRm0Ja-g_Un
"""

from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
m, n = map(int, input("Enter number of  rows and columns").split())
A = array([input("Enter elements row by row  ").strip().split() for _ in range(m)], int)
print(A)
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)
# center columns by subtracting column means
C = A - M
print(C)
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)
# project data
P = vectors.T.dot(C.T)
print(P.T)