# -*- coding: utf-8 -*-
"""lab2q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZAabh2caTw9XDKP67z7n3w9x0UUdO5m

Read the file 'iris.json' as a text file :

  Create a list having each line of the file as an element

  Convert it into a list of dictionary objects.

  Show the details of all flowers whose species is "setosa".

  Print the minimum petal area and max sepal area in each species

  Sort the list of dictionaries according to the total area are sepal and petal.
"""

import json

#function to create a list having each line of the file as an element
def read_as_list(filename):
  print("\t\tList having each line of the file as an element\t\t")
  print("\n")
  fp=open(filename,"r")                             
  data=fp.readlines() 			          #The file elements as list elements
  fp.close()
  return data

#function to convert it into a list of dictionary objects. 
def read_as_dict(filename):
  print("\t\tList of dictionary objects\t\t")
  fp=open(filename,'r')                            
  dictionary=json.load(fp) 	
  return dictionary			 #list of dictionary

#function to show the details of all flowers whose species is "setosa"
def print_details_setosa(data_dict):
  print("\t\tAll flowers whose species is setosa\t\t")
  for i in data_dict:					  #'i' is the dictionary element in the list
    if (i['species']=='setosa'):
        print('Sepel length : %f, '%(i['sepalLength']),'Sepal width : %f, '%(i['sepalWidth']),'Petal length : %f, '%(i['petalLength']),'Petal width : %f, '%(i['petalWidth']))
   
#function to print the minimum petal area and max sepal area in each species
def get_areas(data_dict):
#to print the minimum petal area and max sepal area in each species
  list_species = list()
  for i in data_dict:
    list_species.append(i['species'])  
  list_species = set(list_species)
  print('\n')
  areaSepal = list()
  areaPetal = list()
  for i in list_species:
    print(i.capitalize())
    print("_"*9)
    print(" ")
    for j in data_dict:
      if(j['species']==i):
        areaSepal.append(j['sepalLength']*j['sepalWidth'])
        areaPetal.append(j['petalLength']*j['petalWidth'])
    print("Maximum area of sepal: ",round(max(areaSepal),2))
    print("Minimum area of petal: ",round(min(areaPetal),2))  
    print('\n') 
    areaSepal.clear()
    areaPetal.clear()
  print('\n')

#function to sort the list of dictionaries according to the total area are sepal and petal
def get_total_area(data_dict):
  #Sorting the list of dictionaries according to the total area of sepal and petal.
  print("\t\tList of dictionaries sorted according to the total area of sepal and petal\t\t")
  print("\n")
  copyOfList = list()
  copyOfList = data_dict
  for i in copyOfList:
    petal_area = (i["petalLength"]*i["petalWidth"])
    sepal_area = (i["sepalLength"]*i["sepalWidth"])
    total_area = (petal_area+sepal_area)
    i.update({'total_area':total_area})
  sortedList = (sorted(copyOfList, key = lambda i:i['total_area'] ))
  for i in sortedList:
    print(i)
  
  

#calling functions
data = read_as_list('iris.json')
for line in data:
  print(line)

data_dict = read_as_dict('iris.json')
for row in data_dict:
  print(row)

print_details_setosa(data_dict)
print("\n")
get_areas(data_dict)
get_total_area(data_dict)

