# -*- coding: utf-8 -*-
"""labcycleq3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19VyBg16HTKpR2Vc2PRXC9l4uyfHlLqlw

Develop a program to read the employee's name, code, and basic pay
and calculate the gross salary, deduction, and net salary according to
the following conditions. Define a function to find each of the
components. Finally, generate a payslip.
"""

def gross_salary(BP,DA,HRA,MA): #fuction to find the gross salary
  GS=BP+DA+HRA+MA
  return(GS)
def pay_deduction(PT,PF,IT): #function to find the deduction
  D=PT+PF+IT
  return(D)
def net_salary(GS,D): #function to find the net salary
  netsalary=GS-D
  return(netsalary)
def employee_payslip():

  if(BP<10000):   #finding the components
    DA=(5/100)*BP
    HRA=(2.5/100)*BP
    MA=500
    PT=20
    PF=(8/100)*BP
    IT=0
  elif(BP<30000):
    DA=(7.5/100)*BP
    HRA=(5/100)*BP
    MA=2500
    PT=60
    PF=(8/100)*BP
    IT=0
  elif(BP<50000):
    DA=(11/100)*BP
    HRA=(7.5/100)*BP
    MA=5000
    PT=60
    PF=(11/100)*BP
    IT=(11/100)*BP
  else:
    DA=(2.5/100)*BP
    HRA=(11/100)*BP
    MA=7000
    PT=80
    PF=(12/100)*BP
    IT=(20/100)*BP



  GS = gross_salary(BP,DA,HRA,MA)
  D = pay_deduction(PT,PF,IT)
  netSalary = net_salary(GS,D)
  
  print("\tPAYSLIP\t")

  print("Name of the employee: ",name)
  print("Basic pay:",BP)
  print("Gross salary: ",GS)
  print("Deduction: ",D)
  print("Net Salary: ",netSalary)

name=input("Enter name of the employee: ")  #input details
code=int(input("Enter the code: "))
BP=int(input("Enter basic pay: "))
print("\n")

employee_payslip()
