# -*- coding: utf-8 -*-
"""lab2q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hzSTHaGJZHtLD484LsNQB8OQ4C1V231L

Suppose a newly born pair of rabbits, one male and one female, are
put in a field. Rabbits can mate at the age of one month so that at the
end of its second month, a female has produced another pair of
rabbits. Suppose that our rabbits never die and that the female always
produces one new pair every month from the second month.Develop a program to show a table containing the number of pairs of
rabbits in the first N months
"""

#to input number of months
num = int(input("Enter number of months: "))

#initialising the number of pairs of rabbits
numPair = [1,1]
print("\nMonth\t\tNumber of pairs ")

#the number of rabbits follows a fibonacci sequence

for i in range(0,num):#iteration
  #printing data
  print(i+1,end="\t\t")
  print(numPair[i])
  numPair.append(numPair[i]+numPair[i+1])
