# -*- coding: utf-8 -*-
"""lab2q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wvVLum-OzoEsAXFIKvlSNoqyA82GFPnz

Read the file 'iris.json' as a text file :

1. Create a list having each line of the file as an element
2. Convert it into a list of dictionary objects.
3. Show the details of all flowers whose species is "setosa".
4. Print the minimum petal area and max sepal area in each species
5. Sort the list of dictionaries according to the total area of sepal and petal.
"""

import json
#creating a list having each line of the file as an element 
j_file =  open('/iris.json', 'r')
data = j_file.read()
j_list = json.loads(data)
print("List having each line of the file as an element:")
print(j_list)

#converting to a list of dictionary objects
print("List of dictionary objects formed:")

for i in j_list:
  print(i)

#showing the details of all flowers whose species is "setosa".
print("Details of flowers belonging to setosa species: ")
print("\n")
print("sepalLength\t|sepalWidth\t|petalLength\t|petalWidth")
print("_"*59)
for i in j_list:
  if i['species'] == 'setosa':
    print(i['sepalLength'],"\t\t|",i['sepalWidth'],"\t\t|",i['petalLength'],"\t\t|",i['petalWidth'])

#to print the minimum petal area and max sepal area in each species
list_species = list()
for i in j_list:
  list_species.append(i['species'])  
list_species = set(list_species)
print('\n')
areaSepal = list()
areaPetal = list()
for i in list_species:
  print(i.capitalize())
  print("_"*9)
  print(" ")
  for j in j_list:
    if(j['species']==i):
      areaSepal.append(j['sepalLength']*j['sepalWidth'])
      areaPetal.append(j['petalLength']*j['petalWidth'])
  print("Maximum area of sepal: ",round(max(areaSepal),2))
  print("Minimum area of petal: ",round(min(areaPetal),2))  
  print('\n') 
  areaSepal.clear()
  areaPetal.clear()
print('\n')

#Sorting the list of dictionaries according to the total area of sepal and petal.
copyOfList = list()
copyOfList = j_list
for i in copyOfList:
  petal_area = (i["petalLength"]*i["petalWidth"])
  sepal_area = (i["sepalLength"]*i["sepalWidth"])
  total_area = (petal_area+sepal_area)
  i.update({'total_area':total_area})
sortedList = (sorted(copyOfList, key = lambda i:i['totalArea'] ))
print("The Sorted List")
for i in sortedList:
  print(i)

j_file.close()