# -*- coding: utf-8 -*-
"""lab2q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ag8Jj86yfeXZiTcCS1wH9kRjK_LEdXYJ

Write a program to create a parent class, 3DShapes, with methods printVolume() and printArea(), which prints the Volume and Area, respectively. Create classes Cylinder and Sphere by inheriting 3DShapes class. Using these child classes, calculate and print the volume and area of a cylinder and sphere.
"""

#creating a class shapes3D(acts as a base class)
class Shapes3D:
#functions to print volume and area respectively
  def printVolume(self):
    print("Volume is ",self.volume)
  def printArea(self):
    print("Area is  ",self.area)


#creating a class cylinder(derived class of shapes3D)
class Cylinder(Shapes3D):
  def __init__(self,r,h):
    self.r = r
    self.h = h
    self.area = (2*(22/7)*r*h) + (2*(22/7)*r*r)
    self.volume = ((22/7)*r*r*h)


#creating a class cylinder(derived class of shapes3D)
class Sphere(Shapes3D):
  def __init__(self,r):
    self.r = r
    self.area = 4*(22/7)*r*r
    self.volume = (4/3)*(22/7)*(r**3)


#input dimensions of cylinder
r_cyclinder = int(input("Enter radius of the cylinder: "))
h_cylinder= int(input("Enter height of the cylinder : "))
#c_object is an object of Cylinder
c_object = Cylinder(r_cyclinder,h_cylinder)
print(" ")
print("Cylinder")
print("Volume and area of cylinder:")
c_object.printVolume()
c_object.printArea()

print(" ")
#input dimensions of shere
r_sphere = int(input("Enter the radius of the sphere : "))
#s_object is an object of Cylinder
s_object = Sphere(r_sphere)
print(" ")
print("Sphere")
print("Volume and area of sphere:")
s_object.printVolume()
s_object.printArea()