# -*- coding: utf-8 -*-
"""lab2q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_KX-gfPjHbAl2H-DozLbnXxeQjnziByL

Write a program to read a string containing numbers separated by a space and convert it as a list of integers. Perform the following operations on it.

1. Rotate elements in a list by 'k' position to the right
2. Convert the list into a tuple using list comprehension
3. Remove all duplicates from the tuple and convert them into a list again.
4. Create another list by putting the results of the evaluation of the function 𝑓(𝑥) = 𝑥 2 – 𝑥 with each element in the final list
5. After sorting them individually, merge the two lists to create a single sorted list
"""

#reading string
string_list = input("Enter the list of numbers  : ")
numList = list(string_list.split(" "))

#converting the string input by user to a list of integers
l = []
for i in numList:
  l.append(int(i))
print("List of integers: ",l)
print(" ")

#rotating the elements in the list by 'k' position to the right
k = int(input("Enter the position by which you want to rotate : "))
print("After rotating by",k,"position to right list",end = " = ")
print(l[-k:]+l[:-k])
print(" ")

#converting the ist into a tuple using list comprehension
tuple_l = tuple(l)
print("Tuple: ",tuple_l)
print(" ")

#Removing all duplicates from the tuple and converting them into a list again.
tuple_l = tuple(set(tuple_l))
l = list(tuple_l)
print("After removing duplicates and conversion ",end = " = ")
print(l)
print(" ")

#Creating another list by putting the results of the evaluation of the function 𝑓(𝑥) = 𝑥 2 – 𝑥 with each element in the final list
f = []
for i in l:
  f.append((i**2)-i)
print("List after evaluating function with each element ",end = " = ")
print(f)
print(" ")

#sorting individually and merging to form a single list
finalList = l + f
finalList.sort()
print("Final list ",end = " = ")
print(finalList)
